### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method shareimage on channel flutter_share_file))

### ISSUE THREAD

**Issue by prashant-v-53** [nishantsubedi/flutter_share_file#3]
My log is
```
E/flutter ( 4989): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method shareimage on channel flutter_share_file)
E/flutter ( 4989): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter ( 4989): <asynchronous suspension>
E/flutter ( 4989): #1      FlutterShareFile.shareImage  (package:flutter_share_file/flutter_share_file.dart:13:31)
E/flutter ( 4989): #2      _MyHomePageState.share 
package:app/main.dart:1414
E/flutter ( 4989): #3      _MyHomePageState._previewDownloadedImage.<anonymous closure> 
package:app/main.dart:365
E/flutter ( 4989): #4      TapGestureRecognizer.handleTapDown.<anonymous closure> 
package:flutter/…/gestures/tap.dart:463
E/flutter ( 4989): #5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 4989): #6      TapGestureRecognizer.handleTapDown 
package:flutter/…/gestures/tap.dart:463
E/flutter ( 4989): #7      BaseTapGestureRecognizer._checkDown 
package:flutter/…/gestures/tap.dart:256
E/flutter ( 4989): #8      BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:234
E/flutter ( 4989): #9      GestureArenaManager._resolveByDefault 
package:flutter/…/gestures/arena.dart:250
E/flutter ( 4989): #10     GestureArenaManager._tryToResolveArena.<anonymous closure> 
package:flutter/…/gestures/arena.dart:231
E/flutter ( 4989): #11     _rootRun  (dart:async/zone.dart:1122:38)
E/flutter ( 4989): #12     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter ( 4989): #13     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter ( 4989): #14     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter ( 4989): #15     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter ( 4989): #16     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter ( 4989): #17     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter ( 4989): #18     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter ( 4989): #19     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 4989): #20     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 4989):
```

**Comment by ghost** [comment]
Try to stop debugger then run again
