### ISSUE TITLE
Android Permission Denial

### ISSUE THREAD

**Issue by NuhaKhayat** [nishantsubedi/flutter_share_file#6]
I got below error when sharing in android 
E/DatabaseUtils( 7208): java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.example.fluttersharefile/images/image.png from pid=6607, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 7208): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:804)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:670)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:660)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:540)
E/DatabaseUtils( 7208): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
E/DatabaseUtils( 7208): 	at android.os.Binder.execTransactInternal(Binder.java:1138)
E/DatabaseUtils( 7208): 	at android.os.Binder.execTransact(Binder.java:1102)
E/DatabaseUtils( 7208): Writing exception to parcel
E/DatabaseUtils( 7208): java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.example.fluttersharefile/images/image.png from pid=6607, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 7208): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:804)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:670)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:660)
E/DatabaseUtils( 7208): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:540)
E/DatabaseUtils( 7208): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
E/DatabaseUtils( 7208): 	at android.os.Binder.execTransactInternal(Binder.java:1138)
E/DatabaseUtils( 7208): 	at android.os.Binder.execTransact(Binder.java:1102)

**Comment by NuhaKhayat** [comment]
Still facing the same issue
